"""Explicit typography geometry variants; preserve original raw invocation and content."""
from __future__ import annotations

import copy
import importlib
import json
import math
import tempfile
from pathlib import Path

try:
    from .stylebook_workflow import WORKFLOW, PRODUCER, _peer, _immutable, digest, generation_requests, selected, sha
except ImportError:
    from stylebook_workflow import WORKFLOW, PRODUCER, _peer, _immutable, digest, generation_requests, selected, sha


def apply_layout(manifest: dict, layout: dict) -> dict:
    if not isinstance(layout, dict) or set(layout) != {"version", "items"} or type(layout.get("version")) is not int or layout["version"] != 1:
        raise ValueError("排字调整须为 version=1 与 items 的对象")
    original = manifest.get("text", {})
    items = original.get("items", [])
    if original.get("mode") not in ("overlay", "hybrid") or not items:
        raise ValueError("仅可调整已经明确采用排字模式的现有文字")
    edits = layout["items"]
    if not isinstance(edits, list) or len(edits) != len(items):
        raise ValueError("排字调整须逐项覆盖原有文字，不得新增或删除")
    result = copy.deepcopy(manifest)
    for index, edit in enumerate(edits):
        if not isinstance(edit, dict) or not edit or not set(edit) <= {"box", "font_px", "min_px", "align"}:
            raise ValueError("排字调整只允许位置、字号和对齐，不得改变文字、画风或内容")
        item = result["text"]["items"][index]
        if "box" in edit:
            box = edit["box"]
            if (not isinstance(box, list) or len(box) != 4
                    or any(type(v) not in (int, float) or not math.isfinite(v) for v in box)
                    or any(v < 0 for v in box) or box[2] <= 0 or box[3] <= 0
                    or box[0] + box[2] > 1.000000001 or box[1] + box[3] > 1.000000001):
                raise ValueError("文字区必须在画布内，且宽高大于零")
        for key in ("font_px", "min_px"):
            if key in edit and (type(edit[key]) is not int or not 1 <= edit[key] <= 300):
                raise ValueError("字号必须为有效整数")
        if "align" in edit and edit["align"] not in ("left", "center", "right"):
            raise ValueError("对齐必须为 left、center 或 right")
        item.update(edit)
        if item.get("min_px", 1) < items[index].get("min_px", 1) or item.get("font_px", 48) < item.get("min_px", 1):
            raise ValueError("排字调整不得降低计划的最小可读字号")
    return result


def refit_candidate(cwd: Path, raw_receipt_path: Path, layout_path: Path) -> tuple[dict | None, list[str]]:
    """Refit final lettering on actual generated bytes; no new generation claim."""
    cwd = Path(cwd).resolve()
    try:
        raw_receipt_path = Path(raw_receipt_path).resolve()
        receipt = json.loads(raw_receipt_path.read_text())
        if not selected(receipt) or receipt.get("producer") != PRODUCER or receipt.get("status") != "raw_collected_pending_production":
            raise ValueError("须选择画风库实际回收的原始候选凭证")
        expected_parent = cwd / "素材/stylebook-results" / receipt["request_id"] / receipt["id"]
        if raw_receipt_path.parent != expected_parent or raw_receipt_path.stem != digest(receipt):
            raise ValueError("原始候选凭证已改变或不在本篇不可变结果目录")
        host_path = cwd / receipt["host_request_path"]
        host = json.loads(host_path.read_text())
        pending, errors = generation_requests(cwd, only={item["id"] for item in host["requests"]})
        if errors:
            return None, errors
        current_host = {key: value for key, value in pending.items() if key != "path"}
        if host != current_host or digest(host) != receipt["host_request_digest"] or pending["request_id"] != receipt["request_id"]:
            raise ValueError("原始候选对应的计划/请求已失效，不能制作")
        batch = json.loads((cwd / "素材/render-batch.json").read_text())
        task = next(item for item in batch["tasks"] if item["id"] == receipt["id"])
        host_task = next(item for item in host["requests"] if item["id"] == receipt["id"])
        if digest(task) != receipt["task_digest"] or digest(host_task["call"]) != receipt["actual_call_digest"]:
            raise ValueError("原始候选未绑定当前完整制作任务")
        raw = (cwd / receipt["raw_path"]).resolve()
        if not raw.is_relative_to((cwd / "素材/stylebook-raw" / receipt["request_id"]).resolve()) or sha(raw) != receipt["raw_sha256"]:
            raise ValueError("原始图片路径或字节已改变")
        root, _ = _peer()
        export = importlib.import_module("stylebook.export")
        overlay_module = importlib.import_module("stylebook.overlay")
        textspec = importlib.import_module("stylebook.textspec")
        formats = importlib.import_module("stylebook.data").formats()
        layout_path = Path(layout_path).resolve()
        layout = json.loads(layout_path.read_text())
        manifest = apply_layout(task["manifest"], layout)
        frozen_layout = cwd / "素材/stylebook-layouts" / f"{digest(layout)}.json"
        _immutable(frozen_layout, layout)
        spec = manifest.get("text", {})
        mode = spec.get("mode", formats[manifest["format"]].get("text", {}).get("default", "none"))
        overlay = spec if mode in ("overlay", "hybrid") else None
        dependencies = {str(raw): sha(raw), str(raw_receipt_path): sha(raw_receipt_path),
                        str(host_path): sha(host_path), str(Path(__file__).resolve()): sha(Path(__file__)),
                        str(layout_path): sha(layout_path), str(frozen_layout): sha(frozen_layout)}
        try:
            from . import stylebook_source
        except ImportError:
            import stylebook_source
        plan = json.loads((cwd / "visual-plan.json").read_text())
        source = stylebook_source.current_source(cwd, batch, plan)
        for path in (source, Path(stylebook_source.__file__).resolve(), cwd / "visual-plan.json", cwd / "素材/render-batch.json"):
            dependencies[str(path)] = sha(path)
        dependencies.update({str((root / path).resolve()): value for path, value in batch["method_source"]["files"].items()})
        # Bind the actual font files selected by the same resolver used to draw.
        fonts = []
        if overlay:
            for item in textspec.overlay_items(overlay):
                family, weight = item.get("font_family", "sans"), item.get("weight", "regular")
                font = overlay_module._font(weight, item.get("font_px", 48), family)
                path = Path(font.path).resolve()
                dependencies[str(path)] = sha(path)
                fonts.append({"family": family, "weight": weight, "path": str(path), "index": font.index})
            for layer in overlay.get("image_layers", []):
                path = (cwd / layer["path"]).resolve()
                if not path.is_relative_to(cwd):
                    raise ValueError("图层路径越出文章目录")
                dependencies[str(path)] = sha(path)
        for module in (export, overlay_module, textspec):
            path = Path(module.__file__).resolve()
            if not path.is_relative_to(root):
                raise ValueError("实际制作模块与选定画风库不同")
            dependencies[str(path)] = sha(path)
        import PIL
        with tempfile.TemporaryDirectory(prefix="stylebook-production-", dir=cwd / "素材") as scratch:
            produced = export.export(raw, manifest["format"], Path(scratch) / "final.png", overlay=overlay, overlay_root=cwd)
            if any(sha(Path(path)) != value for path, value in dependencies.items()):
                raise ValueError("最终制作过程中输入或制作方法改变")
            try:
                stylebook_source.current_source(cwd, batch, plan)
            except ValueError as exc:
                raise ValueError(f"最终制作过程中原文或装配内容改变：{exc}") from exc
            outputs = {"main": {"sha256": sha(produced.main)}}
            outputs.update({f"extra-{n}": {"sha256": sha(path)} for n, path in enumerate(produced.extras)})
            identity = {"schema_version": 2, "workflow": WORKFLOW, "producer": PRODUCER,
                        "status": "produced_pending_qa", "request_id": batch["request_id"], "id": receipt["id"],
                        "raw_receipt": str(raw_receipt_path.relative_to(cwd)), "raw_receipt_sha256": sha(raw_receipt_path),
                        "task_digest": digest(task), "manifest": manifest, "dependencies_sha256": dependencies,
                        "production_method": "refit_generated_raw_lettering",
                        "text_layout": {"path": str(frozen_layout.relative_to(cwd)), "sha256": sha(frozen_layout)},
                        "fonts": fonts, "pillow_version": PIL.__version__, "warnings": produced.warnings, "outputs": outputs}
            production_id = digest(identity)
            dest = cwd / "素材/stylebook-final" / batch["request_id"] / receipt["id"] / production_id
            dest.mkdir(parents=True, exist_ok=True)
            files = [("main", produced.main)] + [(f"extra-{n}", path) for n, path in enumerate(produced.extras)]
            for key, path in files:
                target = dest / path.name
                payload = path.read_bytes()
                if target.exists():
                    if target.read_bytes() != payload:
                        raise ValueError("已保存最终候选被改变，拒绝覆盖")
                else:
                    with target.open("xb") as stream:
                        stream.write(payload)
            record = {**identity, "production_id": production_id,
                      "files": {key: str((dest / path.name).relative_to(cwd)) for key, path in files}}
            _immutable(dest / "production.json", record)
        return {**record, "receipt_path": str(dest / "production.json")}, []
    except (OSError, ValueError, KeyError, TypeError, AttributeError, StopIteration) as exc:
        return None, [f"画风库排字调整失败：{exc}"]
